.PHONY: clean All

All:
	@echo "==========Building project:[ ejemplo13 - Debug ]=========="
	@cd "ejemplo13" && "$(MAKE)" -f  "ejemplo13.mk"
clean:
	@echo "==========Cleaning project:[ ejemplo13 - Debug ]----------"
	@cd "ejemplo13" && "$(MAKE)" -f  "ejemplo13.mk" clean
